In [1]:
import numpy as np
import pandas as pd

In [2]:
data_1 = pd.read_csv("data/reddit.csv")
data_1.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [4]:
data_1.shape
data_1.info

<bound method DataFrame.info of                                            clean_comment  category
0       family mormon have never tried explain them t...         1
1      buddhism has very much lot compatible with chr...         1
2      seriously don say thing first all they won get...        -1
3      what you have learned yours and only yours wha...         0
4      for your own benefit you may want read living ...         1
...                                                  ...       ...
37244                                              jesus         0
37245  kya bhai pure saal chutiya banaya modi aur jab...         1
37246              downvote karna tha par upvote hogaya          0
37247                                         haha nice          1
37248             facebook itself now working bjp’ cell          0

[37249 rows x 2 columns]>

In [6]:
data_1.dtypes

clean_comment    object
category          int64
dtype: object

In [7]:
data_1.isnull().sum()

clean_comment    100
category           0
dtype: int64

In [11]:
data_1.dropna(inplace=True)

In [13]:
data_1.isnull().sum()

clean_comment    0
category         0
dtype: int64

In [14]:
data_1["category"] = data_1["category"] + 1

In [15]:
data_1.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         2
1  buddhism has very much lot compatible with chr...         2
2  seriously don say thing first all they won get...         0
3  what you have learned yours and only yours wha...         1
4  for your own benefit you may want read living ...         2

In [17]:
data_1.duplicated().sum()

np.int64(350)

In [18]:
data_1[data_1.duplicated()]

                                           clean_comment  category
375                                                              1
392                                                              1
617                                           aurum mom          1
651                                                              1
1222                                                             1
...                                                  ...       ...
36915                                           who won          1
37044                                                            1
37125                                              hari          1
37158                                           top kek          2
37234  this part series minute videos focusing each d...         2

[350 rows x 2 columns]

In [19]:
data_1.drop_duplicates(inplace=True)

In [20]:
data_1.duplicated().sum()

np.int64(0)

In [21]:
data_1[(data_1["clean_comment"].str.strip() == '')]

                clean_comment  category
181                                   1
4432                       \n         1
10592                                 1
16173                                 1
32149  \n                             1
34959                                 1

In [22]:
data_1[~(data_1["clean_comment"].str.strip() == '')]

                                           clean_comment  category
0       family mormon have never tried explain them t...         2
1      buddhism has very much lot compatible with chr...         2
2      seriously don say thing first all they won get...         0
3      what you have learned yours and only yours wha...         1
4      for your own benefit you may want read living ...         2
...                                                  ...       ...
37244                                              jesus         1
37245  kya bhai pure saal chutiya banaya modi aur jab...         2
37246              downvote karna tha par upvote hogaya          1
37247                                         haha nice          2
37248             facebook itself now working bjp’ cell          1

[36793 rows x 2 columns]

In [23]:
data_1["clean_comment"] = data_1["clean_comment"].str.lower()

In [24]:
data_1.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         2
1  buddhism has very much lot compatible with chr...         2
2  seriously don say thing first all they won get...         0
3  what you have learned yours and only yours wha...         1
4  for your own benefit you may want read living ...         2

In [25]:
data_1["clean_comment"]= data_1["clean_comment"].str.strip()

In [26]:
data_1['clean_comment'] = data_1['clean_comment'].str.replace(r'http\S+|www\S+', '', regex=True)

In [28]:
data_1['clean_comment'] = data_1['clean_comment'].str.replace(r'[\n\r\t]', ' ', regex=True)

In [30]:
data_1.head(15)

                                        clean_comment  category
0   family mormon have never tried explain them th...         2
1   buddhism has very much lot compatible with chr...         2
2   seriously don say thing first all they won get...         0
3   what you have learned yours and only yours wha...         1
4   for your own benefit you may want read living ...         2
5   you should all sit down together and watch the...         0
6   was teens when discovered zen meditation was t...         2
7                             jesus was zen meets jew         1
8   there are two varieties christians dogmatic th...         0
9   dont worry about trying explain yourself just ...         2
10  recently told family that buddhist live the bi...         2
11  unto others you would have them unto you would...         2
12  first understand that you are not anyway contr...         2
13  recently heard similar question where person a...         2
14  different times different cultures same point ...         2

In [31]:
data_2 = pd.read_csv("data/YoutubeCommentsDataSet.csv")

In [32]:
data_2.head()

                                             Comment Sentiment
0  lets not forget that apple pay in 2014 require...   neutral
1  here in nz 50 of retailers don't even have con...  negative
2  i will forever acknowledge this channel with t...  positive
3  whenever i go to a place that doesn't take app...  negative
4  apple pay is so convenient secure and easy to ...  positive

In [37]:
category = []

for x in data_2["Sentiment"]:
    if (x=='neutral'):
        category.append(1)
    elif (x=='negative'):
        category.append(0)
    elif (x=='positive'):
        category.append(2)

data_2['category'] = category

In [38]:
data_2.head()

                                             Comment Sentiment  category
0  lets not forget that apple pay in 2014 require...   neutral         1
1  here in nz 50 of retailers don't even have con...  negative         0
2  i will forever acknowledge this channel with t...  positive         2
3  whenever i go to a place that doesn't take app...  negative         0
4  apple pay is so convenient secure and easy to ...  positive         2

In [47]:
data_2.drop(["Sentiment"], axis=1, inplace=True)

In [48]:
data_1.shape
data_1.info

<bound method DataFrame.info of                                            clean_comment  category
0      family mormon have never tried explain them th...         2
1      buddhism has very much lot compatible with chr...         2
2      seriously don say thing first all they won get...         0
3      what you have learned yours and only yours wha...         1
4      for your own benefit you may want read living ...         2
...                                                  ...       ...
37244                                              jesus         1
37245  kya bhai pure saal chutiya banaya modi aur jab...         2
37246               downvote karna tha par upvote hogaya         1
37247                                          haha nice         2
37248              facebook itself now working bjp’ cell         1

[36799 rows x 2 columns]>

In [49]:
data_2.dtypes

Comment     object
category     int64
dtype: object

In [50]:
data_2.isnull().sum()

Comment     44
category     0
dtype: int64

In [51]:
data_2.dropna(inplace=True)
data_2.isnull().sum()

Comment     0
category    0
dtype: int64

In [55]:
data_2.duplicated().sum()

np.int64(0)

In [53]:
data_2[data_2.duplicated()]

                                                 Comment  category
173    from all the stuff mentioned i have the dji mi...         2
518    happy independence day to ukraine and glory  t...         0
847    linus just turn the key lights 180 and bounce ...         2
848    dan continues to be my new favorite he has suc...         2
849    dan managing to set up his soldering station o...         2
...                                                  ...       ...
18145  explore our free courses with completion certi...         1
18283  thanks for this video very neatly calmly expla...         2
18298  explore our free courses with completion certi...         1
18308  do you want to learn technology from me check ...         1
18348  do you want to learn technology from me check ...         1

[490 rows x 2 columns]

In [54]:
data_2.drop_duplicates(inplace=True)

In [59]:
data_2[(data_2["Comment"].str.strip() == '')]

Empty DataFrame
Columns: [Comment, category]
Index: []

In [61]:
data_2[~(data_2["Comment"].str.strip() == '')]

                                                 Comment  category
0      lets not forget that apple pay in 2014 require...         1
1      here in nz 50 of retailers don't even have con...         0
2      i will forever acknowledge this channel with t...         2
3      whenever i go to a place that doesn't take app...         0
4      apple pay is so convenient secure and easy to ...         2
...                                                  ...       ...
18403  i really like the point about engineering tool...         2
18404  i've just started exploring this field and thi...         2
18405  excelente video con una pregunta filosófica pr...         1
18406  hey daniel just discovered your channel a coup...         2
18407  this is great focus is key a playful approach ...         2

[17874 rows x 2 columns]

In [65]:
data_2["Comment"] = data_2["Comment"].str.strip()

In [66]:
data_2["Comment"] = data_2["Comment"].str.lower()

In [67]:
data_2['Comment'] = data_2['Comment'].str.replace(r'http\S+|www\S+', '', regex=True)
data_2['Comment'] = data_2['Comment'].str.replace(r'[\n\r\t]', ' ', regex=True)

In [68]:
data_2.head(15)

                                              Comment  category
0   lets not forget that apple pay in 2014 require...         1
1   here in nz 50 of retailers don't even have con...         0
2   i will forever acknowledge this channel with t...         2
3   whenever i go to a place that doesn't take app...         0
4   apple pay is so convenient secure and easy to ...         2
5   we've been hounding my bank to adopt apple pay...         1
6   we only got apple pay in south africa in 20202...         2
7   for now i need both apple pay and the physical...         1
8   in the united states we have an abundance of r...         2
9   in cambodia we have a universal qr code system...         1
10  wow you really went to town on the psu test ra...         2
11  the lab is the most exciting thing in it ive s...         2
12  linus im an engineer and love the lmg content ...         2
13  there used to be a time where linus was the sm...         2
14  holy crap i was looking at chroma systems back...         0

In [69]:
data_1.head()

                                       clean_comment  category
0  family mormon have never tried explain them th...         2
1  buddhism has very much lot compatible with chr...         2
2  seriously don say thing first all they won get...         0
3  what you have learned yours and only yours wha...         1
4  for your own benefit you may want read living ...         2

In [71]:
data_2 = data_2.rename(columns={"Comment":"clean_comment"})

In [72]:
data_2.head()

                                       clean_comment  category
0  lets not forget that apple pay in 2014 require...         1
1  here in nz 50 of retailers don't even have con...         0
2  i will forever acknowledge this channel with t...         2
3  whenever i go to a place that doesn't take app...         0
4  apple pay is so convenient secure and easy to ...         2

In [75]:
complete_data = pd.concat([data_1, data_2], axis=0).reset_index(drop=True)

In [84]:
complete_data["clean_comment"].duplicated().sum()

np.int64(255)

In [87]:
complete_data.drop_duplicates(inplace=True)
complete_data["clean_comment"].duplicated().sum()

np.int64(9)

In [89]:
complete_data.to_csv("data/clean_comments.csv")

In [90]:
complete_data['clean_comment'] = (
    complete_data['clean_comment']
    .str.replace(r'http\S+|www\S+', '', regex=True)   # URLs
    .str.replace(r'[^\x00-\x7F]+', ' ', regex=True)   # non-English
    .str.replace(r'\s+', ' ', regex=True)             # normalize spaces
    .str.strip()
)

In [91]:
complete_data.dropna()

                                           clean_comment  category
0      family mormon have never tried explain them th...         2
1      buddhism has very much lot compatible with chr...         2
2      seriously don say thing first all they won get...         0
3      what you have learned yours and only yours wha...         1
4      for your own benefit you may want read living ...         2
...                                                  ...       ...
54668  i really like the point about engineering tool...         2
54669  i've just started exploring this field and thi...         2
54670  excelente video con una pregunta filos fica pr...         1
54671  hey daniel just discovered your channel a coup...         2
54672  this is great focus is key a playful approach ...         2

[54427 rows x 2 columns]

In [92]:
complete_data.to_csv("data/clean_comments.csv")